// <auto-generated />
using System;
using FPIS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPIS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251007185521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPIS.Domain.Models.AccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("AccessTokens", (string)null);
                });

            modelBuilder.Entity("FPIS.Domain.Models.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1026b45e-1aa1-4d6a-9e72-40f9b58871f6"),
                            Key = "EarlyBirdDiscountPercentage",
                            Value = "10"
                        },
                        new
                        {
                            Id = new Guid("1fbec0d0-8fd4-4ce8-b62d-2533ff55ff06"),
                            Key = "EarlyBirdDiscountDaysBefore",
                            Value = "60"
                        },
                        new
                        {
                            Id = new Guid("ddc2be4a-bad6-4602-b34f-2a7b9b5f1502"),
                            Key = "FifthTicketDiscountPercentage",
                            Value = "50"
                        },
                        new
                        {
                            Id = new Guid("5eb344ef-9e7a-4a78-8e3e-23b11f1ed65a"),
                            Key = "FriendPromoDiscountPercentage",
                            Value = "5"
                        });
                });

            modelBuilder.Entity("FPIS.Domain.Models.Concert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Concerts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0ef757c-4fae-46b4-8b20-a0ebc4b9eb7e"),
                            AdditionalInfo = "Open air concert",
                            Address = "Piazza del Colosseo, 1",
                            City = "Rome",
                            Name = "Eros Ramazzotti Live",
                            Venue = "Colosseum"
                        });
                });

            modelBuilder.Entity("FPIS.Domain.Models.ConcertDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("ConcertDates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("faccd7a9-7bab-47a8-9300-296b34a8809e"),
                            ConcertId = new Guid("a0ef757c-4fae-46b4-8b20-a0ebc4b9eb7e"),
                            Date = new DateTime(2027, 11, 15, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a9f9d5ac-9fe2-4141-a1a1-e7e2dba34e4f"),
                            ConcertId = new Guid("a0ef757c-4fae-46b4-8b20-a0ebc4b9eb7e"),
                            Date = new DateTime(2026, 11, 17, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7af48f46-bb1c-4efa-bfe9-37c57de10c00"),
                            ConcertId = new Guid("a0ef757c-4fae-46b4-8b20-a0ebc4b9eb7e"),
                            Date = new DateTime(2025, 11, 19, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FPIS.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfirmedEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("FPIS.Domain.Models.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LinkedReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LinkedReservationId")
                        .IsUnique()
                        .HasFilter("[LinkedReservationId] IS NOT NULL");

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GeneratedPromoCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsedPromoCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UsedPromoCodeId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FPIS.Domain.Models.ReservationTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcertDateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConcertDateId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ReservationTickets");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("111d640b-63d2-42bc-b5a6-79f77463d4fd"),
                            Capacity = 100,
                            Name = "VIP",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("4e9c45c0-a41a-473a-88ad-ef4276bb5301"),
                            Capacity = 500,
                            Name = "Regular",
                            Price = 100.00m
                        });
                });

            modelBuilder.Entity("FPIS.Domain.Models.AccessToken", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Reservation", "Reservation")
                        .WithOne("AccessToken")
                        .HasForeignKey("FPIS.Domain.Models.AccessToken", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("FPIS.Domain.Models.ConcertDate", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Concert", "Concert")
                        .WithMany("Dates")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Discount", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Reservation", "Reservation")
                        .WithMany("Discounts")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("FPIS.Domain.Models.PromoCode", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Reservation", "LinkedReservation")
                        .WithOne("GeneratedPromoCode")
                        .HasForeignKey("FPIS.Domain.Models.PromoCode", "LinkedReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LinkedReservation");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Reservation", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Domain.Models.PromoCode", "UsedPromoCode")
                        .WithMany()
                        .HasForeignKey("UsedPromoCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("UsedPromoCode");
                });

            modelBuilder.Entity("FPIS.Domain.Models.ReservationTicket", b =>
                {
                    b.HasOne("FPIS.Domain.Models.ConcertDate", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ConcertDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Domain.Models.Reservation", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Domain.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Concert", b =>
                {
                    b.Navigation("Dates");
                });

            modelBuilder.Entity("FPIS.Domain.Models.ConcertDate", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Reservation", b =>
                {
                    b.Navigation("AccessToken")
                        .IsRequired();

                    b.Navigation("Discounts");

                    b.Navigation("GeneratedPromoCode")
                        .IsRequired();

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
