// <auto-generated />
#pragma warning disable CS1591
using System;
using FPIS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPIS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPIS.Domain.Models.AccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("AccessTokens", (string)null);
                });

            modelBuilder.Entity("FPIS.Domain.Models.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31ac573d-cae8-46a3-94c5-b27f7312f6d6"),
                            Key = "EarlyBirdDiscountPercentage",
                            Value = "10"
                        },
                        new
                        {
                            Id = new Guid("50b4a649-1e8b-4b89-9b14-f5f8ff15fa5e"),
                            Key = "EarlyBirdDiscountDaysBefore",
                            Value = "60"
                        },
                        new
                        {
                            Id = new Guid("a902686e-36a0-45d2-b334-867bfeff5d52"),
                            Key = "FifthTicketDiscountPercentage",
                            Value = "50"
                        },
                        new
                        {
                            Id = new Guid("39120002-0361-4c5d-8843-7b8776a88bdd"),
                            Key = "FriendPromoDiscountPercentage",
                            Value = "5"
                        });
                });

            modelBuilder.Entity("FPIS.Domain.Models.Concert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Concerts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e874b9e5-6272-4611-8770-b16bfe197985"),
                            AdditionalInfo = "Open air concert",
                            Address = "Piazza del Colosseo, 1",
                            City = "Rome",
                            Name = "Eros Ramazzotti Live",
                            Venue = "Colosseum"
                        });
                });

            modelBuilder.Entity("FPIS.Domain.Models.ConcertDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("ConcertDates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("058736ee-98e1-4238-afc5-9beaf73e4a8f"),
                            ConcertId = new Guid("e874b9e5-6272-4611-8770-b16bfe197985"),
                            Date = new DateTime(2027, 11, 15, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6ab859ea-cef3-4762-9c17-181c6aa1bab3"),
                            ConcertId = new Guid("e874b9e5-6272-4611-8770-b16bfe197985"),
                            Date = new DateTime(2026, 11, 17, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4a7d1d9e-15fc-42da-9fe3-9d6c3fc4f852"),
                            ConcertId = new Guid("e874b9e5-6272-4611-8770-b16bfe197985"),
                            Date = new DateTime(2025, 11, 19, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FPIS.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfirmedEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("FPIS.Domain.Models.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("GeneratedByReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UsedByReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedByReservationId")
                        .IsUnique()
                        .HasFilter("[GeneratedByReservationId] IS NOT NULL");

                    b.HasIndex("UsedByReservationId")
                        .IsUnique()
                        .HasFilter("[UsedByReservationId] IS NOT NULL");

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GeneratedPromoCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsedPromoCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FPIS.Domain.Models.ReservationTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcertDateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConcertDateId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ReservationTickets");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1e62828-6848-43f7-a9b3-2523ec61401e"),
                            Capacity = 100,
                            Name = "VIP",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("019fc76d-c9b1-4708-a516-eaafcb32896d"),
                            Capacity = 500,
                            Name = "Regular",
                            Price = 100.00m
                        });
                });

            modelBuilder.Entity("FPIS.Domain.Models.AccessToken", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Reservation", "Reservation")
                        .WithOne("AccessToken")
                        .HasForeignKey("FPIS.Domain.Models.AccessToken", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("FPIS.Domain.Models.ConcertDate", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Concert", "Concert")
                        .WithMany("Dates")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Discount", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Reservation", "Reservation")
                        .WithMany("Discounts")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("FPIS.Domain.Models.PromoCode", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Reservation", "GeneratedByReservation")
                        .WithOne("GeneratedPromoCode")
                        .HasForeignKey("FPIS.Domain.Models.PromoCode", "GeneratedByReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FPIS.Domain.Models.Reservation", "UsedByReservation")
                        .WithOne("UsedPromoCode")
                        .HasForeignKey("FPIS.Domain.Models.PromoCode", "UsedByReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GeneratedByReservation");

                    b.Navigation("UsedByReservation");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Reservation", b =>
                {
                    b.HasOne("FPIS.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FPIS.Domain.Models.ReservationTicket", b =>
                {
                    b.HasOne("FPIS.Domain.Models.ConcertDate", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ConcertDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Domain.Models.Reservation", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FPIS.Domain.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Concert", b =>
                {
                    b.Navigation("Dates");
                });

            modelBuilder.Entity("FPIS.Domain.Models.ConcertDate", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("FPIS.Domain.Models.Reservation", b =>
                {
                    b.Navigation("AccessToken")
                        .IsRequired();

                    b.Navigation("Discounts");

                    b.Navigation("GeneratedPromoCode")
                        .IsRequired();

                    b.Navigation("Tickets");

                    b.Navigation("UsedPromoCode");
                });
#pragma warning restore 612, 618
        }
    }
}
